name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Hexo website repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v4
          
      - name: Check current directory
        run: |
          pwd
          ls -la

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify your Node.js version
          cache: 'npm'

      - name: install hexo stuff and go
        run: |
            npm install
            npm install hexo-cli -g
            hexo server &  # Run the server in the background
            sleep 5        # Wait for a few seconds to ensure the server is up
            

      # Checkout the Playwright test repository
      - name: Checkout Playwright test repository
        uses: actions/checkout@v4
        with:
          repository: vvh24/IS373-Playwright
          path: IS373-Playwright  # Check out into the specified path

            # Fix permissions for IS373-Playwright directory
      - name: Fix Permissions
        run: |
          sudo chmod -R 755 IS373-Playwright

      - name: Check current directory
        run: |
          pwd
          ls -la

      # Install Playwright dependencies and run tests
      - name: Go Into Valeria folder. Install Playwright dependencies and run tests
        run: |
          cd IS373-Playwright
          npm install
          npx playwright install
          node test.js

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure deployment only happens if the tests pass
    if: github.event_name == 'push'

    steps:
      # Checkout the Hexo repository again (to prevent loss of state)
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Ensure the Node.js version matches

      # Install Hexo and dependencies
      - name: Install Hexo dependencies
        run: |
          npm install
          npm install hexo-cli -g

      # Generate the static website
      - name: Generate Hexo site
        run: hexo generate

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hexo outputs the generated files to the 'public' directory
